### ISSUE TITLE
Dosn't support Django 2.0+

### ISSUE THREAD

**Issue by adi-** [PaesslerAG/django-httpxforwardedfor#5]

**Comment by Eorhim** [comment]
@adi- Did you test it with Django 2.0 or 2.1 or did you rely on documentation? I extended the test set-up to include all current versions in pull request #6 and at least the test passed without changes.

**Comment by zsoldosp** [comment]
@Eorhim I think it's a `setup.py` issue too - see `install_requires` restrictions (somehow `tox` gets around that) https://github.com/PaesslerAG/django-httpxforwardedfor/blob/master/setup.py#L33 (while at it, update the `classifiers` too please)

**Comment by Eorhim** [comment]
@zsoldosp As you can see in my pull request, I addressed that in my last commit. I  mainly wanted to know from the reporter, if there was anything else apart from this meta data.

**Comment by kairichard** [comment]
@adi- we just released a new version to address this issue.
